image: ruby:3.0

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler
  - bundle install

test:
  stage: test
  script:
    - JEKYLL_ENV=development bundle exec jekyll build --config _config.yml,_config.devel.yml --trace --verbose -d test
  artifacts:
    paths:
      - test
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public --config _config.yml,_config.gitlab.yml
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
