title: Worlds Elsewhere Theatre Company
#theme: jekyll-theme-tactile
# logo: /assets/img/logo.png
description: null # hide the description at present.
google-analytics: G-V1LGFXNY4G

layouts_dir: _src/layouts
data_dir: _src/data
includes_dir: _src/includes
sass:
  sass_dir: _src/sass

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "vernon-zero"

markdown: CommonMarkGhPages
commonmark:
  options:
    - SMART             # Use smart punctuation (curly quotes, etc)
    - FOOTNOTES         # Parse footnotes
    # - UNSAFE            # Allow raw/custom HTML and unsafe links
    # - GITHUB_PRE_LANG   # gh-style fenced code blocks
  extensions:
    - autolink        # automatic links <https://github.github.com/gfm/#autolinks-extension->
    - table           # tabular data <https://github.github.com/gfm/#tables-extension->
    - strikethrough   # ~~strikethroughs~~  <https://github.github.com/gfm/#strikethrough-extension->
    # - tasklist        # task lists ( [ ] incomplete; [x] complete ) <https://github.github.com/gfm/#task-list-items-extension->
    # - tagfilter       # Escapes "unsafe" HTML tags <https://github.github.com/gfm/#disallowed-raw-html-extension->
