name: Worlds Elsewhere Theatre Company
title: null #hide the title segment at present; not needed.
theme: jekyll-theme-tactile
# logo: /assets/img/logo.png
description: null # hide the description at present.
# google-analytics: when we want to start tracking views and stuff