title: Worlds Elsewhere Theatre Company
#theme: jekyll-theme-tactile
# logo: /assets/img/logo.png
description: null # hide the description at present.
google_analytics: G-V1LGFXNY4G
timezone: America/New_York
baseurl: ""
url: "https://worlds-elsewhere.com"

# Directory fuckery because I don't love the default "everything in the root" structure
plugins_dir:  _src/plugins
layouts_dir:  _src/layouts
data_dir:     _src/data
includes_dir: _src/includes
sass:
  sass_dir: _src/sass
  sourcemaps: development

redirects: yes
plugins:
  - jekyll-commonmark-ghpages
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-titles-from-headings

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "vernon-zero"

relative_links:
  collections: true

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true

markdown: CommonMarkGhPages
commonmark:
  options:
    - SMART             # Use smart punctuation (curly quotes, etc)
    - FOOTNOTES         # Parse footnotes
    # - UNSAFE            # Allow raw/custom HTML and unsafe links
    # - GITHUB_PRE_LANG   # gh-style fenced code blocks
  extensions:
    - autolink        # automatic links <https://github.github.com/gfm/#autolinks-extension->
    - table           # tabular data <https://github.github.com/gfm/#tables-extension->
    - strikethrough   # ~~strikethroughs~~  <https://github.github.com/gfm/#strikethrough-extension->
    # - tasklist        # task lists ( [ ] incomplete; [x] complete ) <https://github.github.com/gfm/#task-list-items-extension->
    # - tagfilter       # Escapes "unsafe" HTML tags <https://github.github.com/gfm/#disallowed-raw-html-extension->

# Shared site variables which will not be overridden. Access using `site.[x]` (e.g. `site.social.fb.url`)

email: worlds.elsewhere.theatre@gmail.com

social:
  fb: { url: 'https://fb.me/WorldsElsewhere', icon: 'fb', title: 'WorldsElsewhere on Facebook', text: 'fb.me/WorldsElsewhere' }
  yt: { url: 'https://www.youtube.com/channel/UCdMpUSQDs-5P6cgmRSQbAUA', icon: 'yt', title: 'Worlds Elsewhere Theatre Company on Youtube', text: 'Worlds Elsewhere Theatre Company' }
  gram: { url: 'https://instagr.am/worldselsewhere_official', icon: 'gram', title: '@worldselsewhere_official on Instagram', text: '@worldselsewhere_official' }
  twitter: { url: 'https://twitter.com/ElsewhereWorlds', icon: 'twitter', title: '@ElsewhereWorlds on Twitter', text: '@ElsewhereWorlds' }
  news: { url: 'https://worlds-elsewhere.us17.list-manage.com/subscribe?u=8e70862018a339ca07b0f75e6&id=55a342e060', icon: 'news', title: 'Sign up for our Newsletter', text: 'Newsletter' }
