title: Worlds Elsewhere Theatre Company
#theme: jekyll-theme-tactile
# logo: /assets/img/logo.png
description: null # hide the description at present.
# google-analytics: when we want to start tracking views and stuff

layouts_dir: _src/layouts
data_dir: _src/data
includes_dir: _src/includes
markdown: GFM
sass:
  sass_dir: _src/sass

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "vernon-zero"
